Imports Photoshop

Public Class mugColorsSampler_class

    Private Const HEATHER_NAVY_PROOF_X As Double = 163.0
    Private Const HEATHER_NAVY_PROOF_Y As Double = 210.0
    Private Const HEATHER_NAVY_PRINT_X As Double = 383.0
    Private Const HEATHER_NAVY_PRINT_Y As Double = 210.0
    Private Const DARK_HEATHER_PROOF_X As Double = 171.0
    Private Const DARK_HEATHER_PROOF_Y As Double = 514.0
    Private Const DARK_HEATHER_PRINT_X As Double = 367.0
    Private Const DARK_HEATHER_PRINT_Y As Double = 502.0
    Private Const HEATHER_INDIGO_PROOF_X As Double = 171.0
    Private Const HEATHER_INDIGO_PROOF_Y As Double = 802.0
    Private Const HEATHER_INDIGO_PRINT_X As Double = 375.0
    Private Const HEATHER_INDIGO_PRINT_Y As Double = 786.0
    Private Const STONE_BLUE_PROOF_X As Double = 155.0
    Private Const STONE_BLUE_PROOF_Y As Double = 1066.0
    Private Const STONE_BLUE_PRINT_X As Double = 383.0
    Private Const STONE_BLUE_PRINT_Y As Double = 1058.0
    Private Const NAVY_BLUE_PROOF_X As Double = 171.0
    Private Const NAVY_BLUE_PROOF_Y As Double = 1358.0
    Private Const NAVY_BLUE_PRINT_X As Double = 395.0
    Private Const NAVY_BLUE_PRINT_Y As Double = 1350.0
    Private Const AQUATIC_BLUE_PROOF_X As Double = 147.0
    Private Const AQUATIC_BLUE_PROOF_Y As Double = 1594.0
    Private Const AQUATIC_BLUE_PRINT_X As Double = 371.0
    Private Const AQUATIC_BLUE_PRINT_Y As Double = 1606.0
    Private Const INDIGO_BLUE_PROOF_X As Double = 131.0
    Private Const INDIGO_BLUE_PROOF_Y As Double = 1906.0
    Private Const INDIGO_BLUE_PRINT_X As Double = 387.0
    Private Const INDIGO_BLUE_PRINT_Y As Double = 1882.0
    Private Const CAROLINA_BLUE_PROOF_X As Double = 143.0
    Private Const CAROLINA_BLUE_PROOF_Y As Double = 2190.0
    Private Const CAROLINA_BLUE_PRINT_X As Double = 399.0
    Private Const CAROLINA_BLUE_PRINT_Y As Double = 2198.0
    Private Const IRIS_PROOF_X As Double = 143.0
    Private Const IRIS_PROOF_Y As Double = 2482.0
    Private Const IRIS_PRINT_X As Double = 395.0
    Private Const IRIS_PRINT_Y As Double = 2458.0
    Private Const VIOLET_PROOF_X As Double = 171.0
    Private Const VIOLET_PROOF_Y As Double = 2734.0
    Private Const VIOLET_PRINT_X As Double = 399.0
    Private Const VIOLET_PRINT_Y As Double = 2730.0
    Private Const LT_BLUE_PROOF_X As Double = 139.0
    Private Const LT_BLUE_PROOF_Y As Double = 2994.0
    Private Const LT_BLUE_PRINT_X As Double = 395.0
    Private Const LT_BLUE_PRINT_Y As Double = 3002.0
    Private Const HEATHER_MILITARY_PROOF_X As Double = 779.0
    Private Const HEATHER_MILITARY_PROOF_Y As Double = 202.0
    Private Const HEATHER_MILITARY_PRINT_X As Double = 1019.0
    Private Const HEATHER_MILITARY_PRINT_Y As Double = 214.0
    Private Const STONEWASHED_GREEN_PROOF_X As Double = 779.0
    Private Const STONEWASHED_GREEN_PROOF_Y As Double = 498.0
    Private Const STONEWASHED_GREEN_PRINT_X As Double = 1015.0
    Private Const STONEWASHED_GREEN_PRINT_Y As Double = 498.0
    Private Const MILITARY_GREEN_PROOF_X As Double = 787.0
    Private Const MILITARY_GREEN_PROOF_Y As Double = 798.0
    Private Const MILITARY_GREEN_PRINT_X As Double = 1003.0
    Private Const MILITARY_GREEN_PRINT_Y As Double = 794.0
    Private Const FOREST_GREEN_PROOF_X As Double = 767.0
    Private Const FOREST_GREEN_PROOF_Y As Double = 1082.0
    Private Const FOREST_GREEN_PRINT_X As Double = 1023.0
    Private Const FOREST_GREEN_PRINT_Y As Double = 1070.0
    Private Const PISTACHIO_PROOF_X As Double = 759.0
    Private Const PISTACHIO_PROOF_Y As Double = 1322.0
    Private Const PISTACHIO_PRINT_X As Double = 995.0
    Private Const PISTACHIO_PRINT_Y As Double = 1338.0
    Private Const ROYAL_BLUE_PROOF_X As Double = 759.0
    Private Const ROYAL_BLUE_PROOF_Y As Double = 1602.0
    Private Const ROYAL_BLUE_PRINT_X As Double = 1003.0
    Private Const ROYAL_BLUE_PRINT_Y As Double = 1602.0
    Private Const PURPLE_PROOF_X As Double = 783.0
    Private Const PURPLE_PROOF_Y As Double = 1882.0
    Private Const PURPLE_PRINT_X As Double = 999.0
    Private Const PURPLE_PRINT_Y As Double = 1914.0
    Private Const JADE_DOME_PROOF_X As Double = 783.0
    Private Const JADE_DOME_PROOF_Y As Double = 2190.0
    Private Const JADE_DOME_PRINT_X As Double = 995.0
    Private Const JADE_DOME_PRINT_Y As Double = 2202.0
    Private Const COBALT_PROOF_X As Double = 767.0
    Private Const COBALT_PROOF_Y As Double = 2478.0
    Private Const COBALT_PRINT_X As Double = 991.0
    Private Const COBALT_PRINT_Y As Double = 2494.0
    Private Const SAPPHIRE_PROOF_X As Double = 755.0
    Private Const SAPPHIRE_PROOF_Y As Double = 2766.0
    Private Const SAPPHIRE_PRINT_X As Double = 995.0
    Private Const SAPPHIRE_PRINT_Y As Double = 2742.0
    Private Const BLUE_DUSK_PROOF_X As Double = 775.0
    Private Const BLUE_DUSK_PROOF_Y As Double = 3030.0
    Private Const BLUE_DUSK_PRINT_X As Double = 1007.0
    Private Const BLUE_DUSK_PRINT_Y As Double = 3030.0
    Private Const CARDINAL_RED_PROOF_X As Double = 1399.0
    Private Const CARDINAL_RED_PROOF_Y As Double = 270.0
    Private Const CARDINAL_RED_PRINT_X As Double = 1631.0
    Private Const CARDINAL_RED_PRINT_Y As Double = 214.0
    Private Const RED_PROOF_X As Double = 1403.0
    Private Const RED_PROOF_Y As Double = 502.0
    Private Const RED_PRINT_X As Double = 1659.0
    Private Const RED_PRINT_Y As Double = 490.0
    Private Const HEATHER_RED_PROOF_X As Double = 1427.0
    Private Const HEATHER_RED_PROOF_Y As Double = 782.0
    Private Const HEATHER_RED_PRINT_X As Double = 1635.0
    Private Const HEATHER_RED_PRINT_Y As Double = 786.0
    Private Const HEATHER_CARDINAL_PROOF_X As Double = 1439.0
    Private Const HEATHER_CARDINAL_PROOF_Y As Double = 1078.0
    Private Const HEATHER_CARDINAL_PRINT_X As Double = 1635.0
    Private Const HEATHER_CARDINAL_PRINT_Y As Double = 1098.0
    Private Const HELICONIA_PROOF_X As Double = 1383.0
    Private Const HELICONIA_PROOF_Y As Double = 1346.0
    Private Const HELICONIA_PRINT_X As Double = 1383.0
    Private Const HELICONIA_PRINT_Y As Double = 1346.0
    Private Const LT_PINK_PROOF_X As Double = 1423.0
    Private Const LT_PINK_PROOF_Y As Double = 1606.0
    Private Const LT_PINK_PRINT_X As Double = 1423.0
    Private Const LT_PINK_PRINT_Y As Double = 1606.0
    Private Const LAVENDER_PROOF_X As Double = 1399.0
    Private Const LAVENDER_PROOF_Y As Double = 1902.0
    Private Const LAVENDER_PRINT_X As Double = 1631.0
    Private Const LAVENDER_PRINT_Y As Double = 1886.0
    Private Const ORCHID_PROOF_X As Double = 1339.0
    Private Const ORCHID_PROOF_Y As Double = 2166.0
    Private Const ORCHID_PRINT_X As Double = 1659.0
    Private Const ORCHID_PRINT_Y As Double = 2190.0
    Private Const GARNET_PROOF_X As Double = 1411.0
    Private Const GARNET_PROOF_Y As Double = 2478.0
    Private Const GARNET_PRINT_X As Double = 1655.0
    Private Const GARNET_PRINT_Y As Double = 2490.0
    Private Const MAROON_PROOF_X As Double = 1415.0
    Private Const MAROON_PROOF_Y As Double = 2722.0
    Private Const MAROON_PRINT_X As Double = 1631.0
    Private Const MAROON_PRINT_Y As Double = 2742.0
    Private Const METRO_BLUE_PROOF_X As Double = 1439.0
    Private Const METRO_BLUE_PROOF_Y As Double = 3010.0
    Private Const METRO_BLUE_PRINT_X As Double = 1623.0
    Private Const METRO_BLUE_PRINT_Y As Double = 3026.0
    Private Const SANDY_PROOF_X As Double = 2063.0
    Private Const SANDY_PROOF_Y As Double = 230.0
    Private Const SANDY_PRINT_X As Double = 2294.0
    Private Const SANDY_PRINT_Y As Double = 214.0
    Private Const PRAIRIE_DUST_PROOF_X As Double = 2063.0
    Private Const PRAIRIE_DUST_PROOF_Y As Double = 482.0
    Private Const PRAIRIE_DUST_PRINT_X As Double = 2282.0
    Private Const PRAIRIE_DUST_PRINT_Y As Double = 486.0
    Private Const NATURAL_PROOF_X As Double = 2079.0
    Private Const NATURAL_PROOF_Y As Double = 786.0
    Private Const NATURAL_PRINT_X As Double = 2290.0
    Private Const NATURAL_PRINT_Y As Double = 762.0
    Private Const DARK_CHOCOLATE_PROOF_X As Double = 2071.0
    Private Const DARK_CHOCOLATE_PROOF_Y As Double = 1090.0
    Private Const DARK_CHOCOLATE_PRINT_X As Double = 2278.0
    Private Const DARK_CHOCOLATE_PRINT_Y As Double = 1110.0
    Private Const SAND_PROOF_X As Double = 2043.0
    Private Const SAND_PROOF_Y As Double = 1334.0
    Private Const SAND_PRINT_X As Double = 2302.0
    Private Const SAND_PRINT_Y As Double = 1330.0
    Private Const BROWN_SAVANA_PROOF_X As Double = 2087.0
    Private Const BROWN_SAVANA_PROOF_Y As Double = 1610.0
    Private Const BROWN_SAVANA_PRINT_X As Double = 2278.0
    Private Const BROWN_SAVANA_PRINT_Y As Double = 1626.0
    Private Const CHESTNUT_PROOF_X As Double = 2107.0
    Private Const CHESTNUT_PROOF_Y As Double = 1898.0
    Private Const CHESTNUT_PRINT_X As Double = 2326.0
    Private Const CHESTNUT_PRINT_Y As Double = 1906.0
    Private Const HEATHER_DARK_CHOCOLATE_PROOF_X As Double = 2091.0
    Private Const HEATHER_DARK_CHOCOLATE_PROOF_Y As Double = 2174.0
    Private Const HEATHER_DARK_CHOCOLATE_PRINT_X As Double = 2091.0
    Private Const HEATHER_DARK_CHOCOLATE_PRINT_Y As Double = 2174.0
    Private Const IRISH_GREEN_PROOF_X As Double = 2087.0
    Private Const IRISH_GREEN_PROOF_Y As Double = 2478.0
    Private Const IRISH_GREEN_PRINT_X As Double = 2294.0
    Private Const IRISH_GREEN_PRINT_Y As Double = 2474.0
    Private Const HEATHER_FOREST_PROOF_X As Double = 2091.0
    Private Const HEATHER_FOREST_PROOF_Y As Double = 2750.0
    Private Const HEATHER_FOREST_PRINT_X As Double = 2259.0
    Private Const HEATHER_FOREST_PRINT_Y As Double = 2778.0
    Private Const ANTIQUE_JADE_DOME_PROOF_X As Double = 2103.0
    Private Const ANTIQUE_JADE_DOME_PROOF_Y As Double = 3018.0
    Private Const ANTIQUE_JADE_DOME_PRINT_X As Double = 2331.0
    Private Const ANTIQUE_JADE_DOME_PRINT_Y As Double = 3015.0
    Private Const CHARCOAL_PROOF_X As Double = 2719.0
    Private Const CHARCOAL_PROOF_Y As Double = 215.0
    Private Const CHARCOAL_PRINT_X As Double = 2919.0
    Private Const CHARCOAL_PRINT_Y As Double = 231.0
    Private Const SPORTS_GREY_PROOF_X As Double = 2695.0
    Private Const SPORTS_GREY_PROOF_Y As Double = 479.0
    Private Const SPORTS_GREY_PRINT_X As Double = 2951.0
    Private Const SPORTS_GREY_PRINT_Y As Double = 491.0
    Private Const KIWI_PROOF_X As Double = 2699.0
    Private Const KIWI_PROOF_Y As Double = 795.0
    Private Const KIWI_PRINT_X As Double = 2927.0
    Private Const KIWI_PRINT_Y As Double = 811.0
    Private Const ANTIQUE_SAPPHIRE_PROOF_X As Double = 2719.0
    Private Const ANTIQUE_SAPPHIRE_PROOF_Y As Double = 1071.0
    Private Const ANTIQUE_SAPPHIRE_PRINT_X As Double = 2931.0
    Private Const ANTIQUE_SAPPHIRE_PRINT_Y As Double = 1071.0
    Private Const GRAPHITE_HEATHER_PROOF_X As Double = 2719.0
    Private Const GRAPHITE_HEATHER_PROOF_Y As Double = 1347.0
    Private Const GRAPHITE_HEATHER_PRINT_X As Double = 2911.0
    Private Const GRAPHITE_HEATHER_PRINT_Y As Double = 1327.0
    Private Const BLACKBERRY_PROOF_X As Double = 2447.0
    Private Const BLACKBERRY_PROOF_Y As Double = 1899.0
    Private Const BLACKBERRY_PRINT_X As Double = 2947.0
    Private Const BLACKBERRY_PRINT_Y As Double = 1883.0
    Private Const MIDNIGHT_PROOF_X As Double = 2731.0
    Private Const MIDNIGHT_PROOF_Y As Double = 2151.0
    Private Const MIDNIGHT_PRINT_X As Double = 2959.0
    Private Const MIDNIGHT_PRINT_Y As Double = 2167.0
    Private Const HONEY_PROOF_X As Double = 3346.0
    Private Const HONEY_PROOF_Y As Double = 207.0
    Private Const HONEY_PRINT_X As Double = 3538.0
    Private Const HONEY_PRINT_Y As Double = 223.0
    Private Const DAFFODIL_PROOF_X As Double = 3343.0
    Private Const DAFFODIL_PROOF_Y As Double = 479.0
    Private Const DAFFODIL_PRINT_X As Double = 3343.0
    Private Const DAFFODIL_PRINT_Y As Double = 479.0
    Private Const DAISY_PROOF_X As Double = 3358.0
    Private Const DAISY_PROOF_Y As Double = 799.0
    Private Const DAISY_PRINT_X As Double = 3562.0
    Private Const DAISY_PRINT_Y As Double = 803.0
    Private Const TEXAS_ORANGE_PROOF_X As Double = 3374.0
    Private Const TEXAS_ORANGE_PROOF_Y As Double = 1091.0
    Private Const TEXAS_ORANGE_PRINT_X As Double = 3566.0
    Private Const TEXAS_ORANGE_PRINT_Y As Double = 1075.0
    Private Const ANTIQUE_ORANGE_PRINT_X As Double = 3366.0
    Private Const ANTIQUE_ORANGE_PRINT_Y As Double = 1391.0
    Private Const ANTIQUE_ORANGE_PROOF_X As Double = 3554.0
    Private Const ANTIQUE_ORANGE_PROOF_Y As Double = 1379.0
    Private Const ANTIQUE_CHERRY_PRINT_X As Double = 3358.0
    Private Const ANTIQUE_CHERRY_PRINT_Y As Double = 1647.0
    Private Const ANTIQUE_CHERRY_PROOF_X As Double = 3558.0
    Private Const ANTIQUE_CHERRY_PROOF_Y As Double = 1659.0
    Private Const ORANGE_PRINT_X As Double = 3346.0
    Private Const ORANGE_PRINT_Y As Double = 1927.0
    Private Const ORANGE_PROOF_X As Double = 3566.0
    Private Const ORANGE_PROOF_Y As Double = 1927.0


    Public Enum MUG_COLOR As Integer

        HEATHER_NAVY_PROOF = 0
        HEATHER_NAVY_PRINT = 1
        DARK_HEATHER_PROOF = 2
        DARK_HEATHER_PRINT = 3
        HEATHER_INDIGO_PROOF = 4
        HEATHER_INDIGO_PRINT = 5
        STONE_BLUE_PROOF = 6
        STONE_BLUE_PRINT = 7
        NAVY_BLUE_PROOF = 8
        NAVY_BLUE_PRINT = 9
        AQUATIC_BLUE_PROOF = 10
        AQUATIC_BLUE_PRINT = 11
        INDIGO_BLUE_PROOF = 12
        INDIGO_BLUE_PRINT = 13
        CAROLINA_BLUE_PROOF = 14
        CAROLINA_BLUE_PRINT = 15
        IRIS_PROOF = 16
        IRIS_PRINT = 17
        VIOLET_PROOF = 18
        VIOLET_PRINT = 19
        LT_BLUE_PROOF = 20
        LT_BLUE_PRINT = 21
        HEATHER_MILITARY_PROOF = 22
        HEATHER_MILITARY_PRINT = 23
        STONEWASHED_GREEN_PROOF = 24
        STONEWASHED_GREEN_PRINT = 25
        MILITARY_GREEN_PROOF = 26
        MILITARY_GREEN_PRINT = 27
        FOREST_GREEN_PROOF = 28
        FOREST_GREEN_PRINT = 29
        PISTACHIO_PROOF = 30
        PISTACHIO_PRINT = 31
        ROYAL_BLUE_PROOF = 32
        ROYAL_BLUE_PRINT = 33
        PURPLE_PROOF = 34
        PURPLE_PRINT = 35
        JADE_DOME_PROOF = 36
        JADE_DOME_PRINT = 37
        COBALT_PROOF = 38
        COBALT_PRINT = 39
        SAPPHIRE_PROOF = 40
        SAPPHIRE_PRINT = 41
        BLUE_DUSK_PROOF = 42
        BLUE_DUSK_PRINT = 43
        CARDINAL_RED_PROOF = 44
        CARDINAL_RED_PRINT = 45
        RED_PROOF = 46
        RED_PRINT = 47
        HEATHER_RED_PROOF = 48
        HEATHER_RED_PRINT = 49
        HEATHER_CARDINAL_PROOF = 50
        HEATHER_CARDINAL_PRINT = 51
        HELICONIA_PROOF = 52
        HELICONIA_PRINT = 53
        LT_PINK_PROOF = 54
        LT_PINK_PRINT = 55
        LAVENDER_PROOF = 56
        LAVENDER_PRINT = 57
        ORCHID_PROOF = 58
        ORCHID_PRINT = 59
        GARNET_PROOF = 60
        GARNET_PRINT = 61
        MAROON_PROOF = 62
        MAROON_PRINT = 63
        METRO_BLUE_PROOF = 64
        METRO_BLUE_PRINT = 65
        SANDY_PROOF = 66
        SANDY_PRINT = 67
        PRAIRIE_DUST_PROOF = 68
        PRAIRIE_DUST_PRINT = 69
        NATURAL_PROOF = 70
        NATURAL_PRINT = 71
        DARK_CHOCOLATE_PROOF = 72
        DARK_CHOCOLATE_PRINT = 73
        SAND_PROOF = 74
        SAND_PRINT = 75
        BROWN_SAVANA_PROOF = 76
        BROWN_SAVANA_PRINT = 77
        CHESTNUT_PROOF = 78
        CHESTNUT_PRINT = 79
        HEATHER_DARK_CHOCOLATE_PROOF = 80
        HEATHER_DARK_CHOCOLATE_PRINT = 81
        IRISH_GREEN_PROOF = 82
        IRISH_GREEN_PRINT = 83
        HEATHER_FOREST_PROOF = 84
        HEATHER_FOREST_PRINT = 85
        ANTIQUE_JADE_DOME_PROOF = 86
        ANTIQUE_JADE_DOME_PRINT = 87
        CHARCOAL_PROOF = 88
        CHARCOAL_PRINT = 89
        SPORTS_GREY_PROOF = 90
        SPORTS_GREY_PRINT = 91
        KIWI_PROOF = 92
        KIWI_PRINT = 93
        ANTIQUE_SAPPHIRE_PROOF = 94
        ANTIQUE_SAPPHIRE_PRINT = 95
        GRAPHITE_HEATHER_PROOF = 96
        GRAPHITE_HEATHER_PRINT = 97
        BLACKBERRY_PROOF = 98
        BLACKBERRY_PRINT = 99
        MIDNIGHT_PROOF = 100
        MIDNIGHT_PRINT = 101
        HONEY_PROOF = 102
        HONEY_PRINT = 103
        DAFFODIL_PROOF = 104
        DAFFODIL_PRINT = 105
        DAISY_PROOF = 106
        DAISY_PRINT = 107
        TEXAS_ORANGE_PROOF = 108
        TEXAS_ORANGE_PRINT = 109
        ANTIQUE_ORANGE_PRINT = 110
        ANTIQUE_ORANGE_PROOF = 111
        ANTIQUE_CHERRY_PRINT = 112
        ANTIQUE_CHERRY_PROOF = 113
        ORANGE_PRINT = 114
        ORANGE_PROOF = 115

    End Enum

    Public Function GetRGBColorFromShirtColors_NEWFile(ByRef app As Application, ByVal MugColor As MUG_COLOR) As RGBColor

        Dim previousUnitPreference As PsUnits = app.Preferences.RulerUnits
        app.Preferences.RulerUnits = PsUnits.psPixels
        Dim swatchDoc As Document = app.Open("\\ARTSERVER\Textile-Misc\Textile Files\In Progress & Ideas\MUGS\Shirt Colors_NEW.psd")

        app.ActiveDocument.ColorSamplers.RemoveAll()

        Dim position(1) As Object 'the array passed to colorsampler.add MUST be type 'Object' to avoid throwing an error!
        position(0) = 191.0
        position(1) = 240.0
        Dim pointSample As ColorSampler = app.ActiveDocument.ColorSamplers.Add(position)

        Dim finalRGB As New RGBColor
        finalRGB.Red = pointSample.Color.RGB.Red
        finalRGB.Green = pointSample.Color.RGB.Green
        finalRGB.Blue = pointSample.Color.RGB.Blue

        pointSample.Delete()

        app.Preferences.RulerUnits = previousUnitPreference 'restore previous ruler units preference
        swatchDoc.Close(PsSaveOptions.psDoNotSaveChanges)

        Return finalRGB

    End Function

End Class
